[package]
name = "threads_comparison"
version = "0.1.0"
edition = "2021"
[dependencies]
image = "0.25.6"
windows = { version = "0.61.1", features = ["Win32_System_Threading", "Win32_Foundation", "Win32_System_ProcessStatus"] }
threadpool = "1.8"
num_cpus = "1.16.0"
